[build]
  command   = "node build.js"
  publish   = "."

# Garante que o config.js gerado não é cacheado pelo browser
[[headers]]
  for = "/config.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

# Garante que o index.html também não é cacheado
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
